### ISSUE TITLE
org.xml.sax.SAXParseException  Premature end of file

### ISSUE THREAD

**Issue by coolbeevip** [kevinherron/uanodeset-parser#6]
I created an XML file with the following content
NOTE：element value

```xml
  <UAVariable NodeId="i=104" BrowseName="DataTypeVersion" ParentNodeId="i=58" DataType="String">
    <Value>0</Value>
  </UAVariable>
```

I use the method `UaNodeSet.parse()` to parse it and I get the following error

```
[Fatal Error] :1:1: Premature end of file。
[main] WARN com.digitalpetri.opcua.nodeset.util.AttributeUtil - unable to parse Value: 
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file。
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.eclipse.milo.opcua.stack.core.serialization.OpcUaXmlStreamDecoder.setInput(OpcUaXmlStreamDecoder.java:110)
	at org.eclipse.milo.opcua.stack.core.serialization.OpcUaXmlStreamDecoder.setInput(OpcUaXmlStreamDecoder.java:106)
	at com.digitalpetri.opcua.nodeset.util.AttributeUtil.parseValue(AttributeUtil.java:126)
	at com.digitalpetri.opcua.nodeset.attributes.VariableNodeAttributes.value(VariableNodeAttributes.java:166)
	at com.digitalpetri.opcua.nodeset.attributes.VariableNodeAttributes.fromGenerated(VariableNodeAttributes.java:130)
	at com.digitalpetri.opcua.nodeset.UaNodeSet.lambda$new$5(UaNodeSet.java:141)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.digitalpetri.opcua.nodeset.UaNodeSet.<init>(UaNodeSet.java:119)
	at com.digitalpetri.opcua.nodeset.UaNodeSet.parse(UaNodeSet.java:236)
	at com.digitalpetri.opcua.nodeset.UaNodeSetTest.parse(UaNodeSetTest.java:94)
	at com.digitalpetri.opcua.nodeset.UaNodeSetTest.testParseHollySysNodeSet(UaNodeSetTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Parsed schema/Opc.Ua.NodeSet.Schema.EmptyReferences.xml and generated 2 nodes.

Process finished with exit code 0
```

This problem can be solved after modifying VariableNodeAttributes.java the following

```
private static DataValue value(
    UAVariable.Value gValue,
    Marshaller marshaller,
    NodeId nodeId,
    Map<NodeId, String> rawXmlValues
) {
    Optional optional = Optional.ofNullable(gValue).map(UAVariable.Value::getAny);
    if(optional.isPresent()){
        return AttributeUtil.parseValue(gValue.getAny(), marshaller, nodeId, rawXmlValues);
    }else{
        return new DataValue(Variant.NULL_VALUE);
    }
}
```

**Comment by kevinherron** [comment]
I don't know if `<Value>0</Value>` is valid because the schema says it should be a complex type but I've fixed the NPE anyway. Thanks for reporting.

**Comment by coolbeevip** [comment]
> I don't know if `<Value>0</Value>` is valid because the schema says it should be a complex type but I've fixed the NPE anyway. Thanks for reporting.

You are correct
